name: yala
description: SME Payment App

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_hooks: ^0.6.0
  graphql_flutter: ^2.1.0
  mobx: ^0.3.5
  flutter_mobx: ^0.3.0+1
  back_button_interceptor: ^4.0.7
  shape_of_view: ^1.0.1
  page_transition: ^1.1.4
  animated_card: ^1.0.0+6
  sliver_animated_list: ^0.0.1+1
  rect_getter: ^0.0.1
  locales: ^0.1.0
  intl: ^0.15.8
  enum_to_string: ^1.0.7
  bezier_chart: ^1.0.13
  after_layout: ^1.0.7+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5

builders:
  mobx_codegen: ^0.3.3+1

flutter:
  uses-material-design: true
  
  assets:
   - assets/images/
 
  fonts:
      - family: FontAwesome5ProLight
        fonts:
          - asset: assets/fonts/Icons/FontAwesome_3_7_2/FontAwesome5Pro-Light.otf
      - family: FontAwesome5ProRegular
        fonts:
          - asset: assets/fonts/Icons/FontAwesome_3_7_2/FontAwesome5Pro-Regular.otf
      - family: FontAwesome5ProSolid
        fonts:
          - asset: assets/fonts/Icons/FontAwesome_3_7_2/FontAwesome5Pro-Solid.otf
      
      - family: DINNextRoundedLTPro
        fonts:
          - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Light.ttf
            weight: 300
          - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Regular.ttf
            weight: 400
          - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Medium.ttf
            weight: 500
          - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Bold.ttf
            weight: 700

      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/Roboto/Roboto-Light.ttf
            weight: 300
          - asset: assets/fonts/Roboto/Roboto-Regular.ttf
            weight: 400
          - asset: assets/fonts/Roboto/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/Roboto/Roboto-Bold.ttf
            weight: 700
          - asset: assets/fonts/Roboto/Roboto-Black.ttf
            weight: 900