name: yala
description: SME Payment App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/Roboto/Roboto-Light.ttf
            weight: 300
          - asset: assets/fonts/Roboto/Roboto-Regular.ttf
            weight: 400
          - asset: assets/fonts/Roboto/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/Roboto/Roboto-Bold.ttf
            weight: 700
          - asset: assets/fonts/Roboto/Roboto-Black.ttf
            weight: 900
      - family: DINNextRoundedLTPro
        fonts:
          - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Light.otf
            weight: 300
          - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Regular.otf
            weight: 400
          - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Medium.otf
            weight: 500
          - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Bold.otf
            weight: 700