name: yala
description: SME Payment App

version: 1.0.0+2

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.6.0
  graphql_flutter: ^2.1.0
  mobx: ^0.3.7
  flutter_mobx: ^0.3.2
  back_button_interceptor: ^4.1.1
  shape_of_view: ^1.0.1
  page_transition: ^1.1.4
  animated_card: ^1.0.0+6
  sliver_animated_list: ^1.0.0+2
  locales: ^0.1.0
  intl: ^0.16.0
  enum_to_string: ^1.0.7
  after_layout: ^1.0.7+2
  provider: ^3.1.0
  dotted_border: ^1.0.2
  random_color: ^1.0.3
  autocomplete_textfield: ^1.7.3
  flutter_screenutil: ^0.6.0
  vector_math: ^2.0.8
  uuid: ^2.0.2
  direct_select_flutter: ^1.0.4
  flutter_datetime_picker: ^1.2.6
  flutter_masked_text: ^0.8.0
  mask_text_input_formatter: ^1.0.2

builders:
  mobx_codegen: ^0.3.5

dev_dependencies:
  build_runner: ^1.6.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/

  fonts:
    - family: FontAwesome5ProLight
      fonts:
        - asset: assets/fonts/Icons/FontAwesome_3_7_2/FontAwesome5Pro-Light.otf
    - family: FontAwesome5ProRegular
      fonts:
        - asset: assets/fonts/Icons/FontAwesome_3_7_2/FontAwesome5Pro-Regular.otf
    - family: FontAwesome5ProSolid
      fonts:
        - asset: assets/fonts/Icons/FontAwesome_3_7_2/FontAwesome5Pro-Solid.otf

    - family: DINNextRoundedLTPro
      fonts:
        - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Light.ttf
          weight: 300
        - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/DINNextRoundedLTPro/DINNextRoundedLTPro-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
